# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 22:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibu', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('abv', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(18)])),
                ('srm', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('og', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(2.0)])),
                ('fg', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.8), django.core.validators.MaxValueValidator(2.0)])),
                ('fuzziness', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.CharField(editable=False, max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('ibuMin', models.PositiveSmallIntegerField()),
                ('ibuMax', models.PositiveSmallIntegerField()),
                ('abvMin', models.DecimalField(decimal_places=2, max_digits=4)),
                ('abvMax', models.DecimalField(decimal_places=2, max_digits=4)),
                ('srmMin', models.PositiveSmallIntegerField()),
                ('srmMax', models.PositiveSmallIntegerField()),
                ('ogMin', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ogMax', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fgMin', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fgMax', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='recommendation',
            name='styles',
            field=models.ManyToManyField(to='recommender.Style'),
        ),
    ]
