# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20170717_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='desc',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='fg',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='ibu',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='og',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='srm',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
