# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20170720_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
