# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_auto_20170720_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='label',
            field=models.URLField(null=True),
        ),
    ]
