# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_beer_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='allowNull',
            field=models.BooleanField(default=False),
        ),
    ]
