# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_remove_recommendation_allownull'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='brewery',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='beers',
            field=models.ManyToManyField(to='beerdata.Beer'),
        ),
        migrations.DeleteModel(
            name='Beer',
        ),
        migrations.DeleteModel(
            name='Brewery',
        ),
    ]
