# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.CharField(editable=False, max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('desc', models.TextField(null=True)),
                ('ibu', models.PositiveSmallIntegerField(null=True)),
                ('abv', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('srm', models.PositiveSmallIntegerField(null=True)),
                ('og', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('fg', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('label', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.CharField(editable=False, max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('lat', models.CharField(max_length=256)),
                ('lng', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerdata.Brewery'),
        ),
    ]
