# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='body',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
